### PR TITLE
PL strings v2.9

### PR DESCRIPTION
**Pull request by SpontanCombust**

### CODE REVIEW

**Comment by Aelto** [comment]
Thank you for the translation! ♥

**Comment by Aelto** [comment]
I had pending change i just pushed to the csv if you're interested. I added a line at the end and replaced the key `rer_arachnophobia_mode` with `option_rer_arachnophobia_mode`. If you wish to be future proof you can update it right now

**Comment by SpontanCombust** [comment]
Yeah, don't merge yet. I'll do the change later today.

**Comment by Aelto** [comment]
Thanks for taking the time to update the CSV again, i'll merge it now!

**Pull request merged**
