### PR TITLE
Compile error fixes for tracker.wss

### PR DESCRIPTION
**Pull request by Pav-Osmolski**

### CODE REVIEW

**Comment by Pav-Osmolski** [comment]
Oh you beat me to it!

That was me in the Nexus forum btw, gofftiddums.

Thanks!

**Comment by Aelto** [comment]
Ah! well thanks for the PR ahah. I must say i'm impressed you managed to get it to compile and bundle a release when there is little to no documentation on the subject.

And yes Faen and I worked on the sharedutils recently and his last POTP update includes our recent changes to the modules. I initially wanted to finish what i was working on before pushing a release to avoid having 2 releases back to back but i've been so busy i couldn't even work on what i wanted to add... So i guess i'll push the update right now!

**Comment by Pav-Osmolski** [comment]
> Ah! well thanks for the PR ahah. I must say i'm impressed you managed to get it to compile and bundle a release when there is little to no documentation on the subject.
> 
> And yes Faen and I worked on the sharedutils recently and his last POTP update includes our recent changes to the modules. I initially wanted to finish what i was working on before pushing a release to avoid having 2 releases back to back but i've been so busy i couldn't even work on what i wanted to add... So i guess i'll push the update right now!

No problem! Getting it to compile wasn't too tricky, but I did have to make a few cmd fixes which I also included in this PR. I added /D flag to the change directory command which resolve my issues with the script not being able to hop around. Also wrapped %modkitpath% in quotations because I have the mod tools installed in Program Files.

**Comment by Aelto** [comment]
Excellent, thanks for the tweaks to the scripts. I'm always for more robust scripts, batch isn't my strong suit so i'll trust you on the `/D` flag on the CD!

I'm merging the PR

**Pull request merged**
